version: '3.8'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: WyEBcUPh
      MYSQL_DATABASE: notes-app
      MYSQL_USER: notes-app
      MYSQL_PASSWORD: WyEBcUPh