services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    networks:
      - default
    depends_on:
      - postgres
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=notes-app'
      - 'POSTGRES_PASSWORD=2tg7c0VKZcBUcM3zMZ4c'
      - 'POSTGRES_USER=notes-app'
    ports:
      - '5432:5432'
    networks:
      - default
networks:
  default:
    driver: bridge