server:
  port: 8080

spring:
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
  datasource:
    url: jdbc:mysql://localhost:3306/notes-app
    username: notes-app
    password: WyEBcUPh

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true