server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notes-app
    username: notes-app
    password: WyEBcUPh

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true